-- Supabase RLS readiness notes for the information-room reservation app.
--
-- Do not run this file as a production migration. The app currently uses
-- Riro auth + Prisma sessions, not Supabase Auth. Policies based on auth.uid()
-- are ineffective for Prisma requests unless a trusted user context is passed
-- to Postgres for every transaction.

-- Safe rollout order:
-- 1. Create a limited runtime database role for the app instead of using a
--    table-owner role from DATABASE_URL.
-- 2. Wrap every Prisma request that reads/writes user-scoped data in a
--    transaction that sets trusted request variables, for example:
--      set local app.current_user_id = '<session user id>';
--      set local app.current_user_role = 'STUDENT' | 'ADMIN';
-- 3. Write RLS policies against current_setting('app.current_user_id', true)
--    and current_setting('app.current_user_role', true), not auth.uid().
-- 4. Add integration tests that prove direct cross-user reads/writes fail
--    through the same runtime DATABASE_URL used by Vercel.
-- 5. Enable RLS table by table. Only use FORCE ROW LEVEL SECURITY after the
--    runtime role and transaction context are proven in production-like smoke.

-- Example shape only:
--
-- alter table "Reservation" enable row level security;
--
-- create policy reservation_student_own_rows
-- on "Reservation"
-- for select
-- using (
--   current_setting('app.current_user_role', true) = 'ADMIN'
--   or "userId" = current_setting('app.current_user_id', true)
-- );
--
-- create policy reservation_student_insert_own_rows
-- on "Reservation"
-- for insert
-- with check (
--   current_setting('app.current_user_role', true) = 'ADMIN'
--   or "userId" = current_setting('app.current_user_id', true)
-- );
